version: '3.1'
services:
  web:
    build: .
    ports:
      - "80:8080"
    environment:
      - PORT=8080
      - GEMINI_API_KEY=SUA_CHAVE_DA_API
    volumes:
      - ./temp-uploads:/app/temp-uploads
